import '../models/pomodoro_session.dart';
import 'auth_service.dart';
import 'database_service.dart';
import 'sync_service.dart';
import 'api_service.dart';

/// High-level helpers to record and read Pomodoro sessions.
class SessionService {
  SessionService._();
  static final SessionService instance = SessionService._();

  /// Record a completed Pomodoro session locally.
  /// Automatically attempts to sync if a user is logged in and online.
  Future<PomodoroSession> recordCompletedSession(int durationMinutes) async {
    final user = AuthService.instance.currentUser;
    final nowMs = DateTime.now().millisecondsSinceEpoch;
    final session = PomodoroSession(
      id: '', // UUID will be generated by DatabaseService
      userId: user?.id,
      duration: durationMinutes,
      completedAt: nowMs,
      synced: false,
    );
    final saved = await DatabaseService.instance.insertSession(session);

    // Trigger a sync attempt
    await SyncService.instance.syncUnsyncedSessionsForCurrentUser();
    return saved;
  }

  /// List all sessions for the current user. If not logged in, returns all local sessions.
  Future<List<PomodoroSession>> listSessionsForCurrentUser() async {
    final user = AuthService.instance.currentUser;
    return DatabaseService.instance.getSessions(userId: user?.id);
  }

  /// Merge local and remote sessions for the current user.
  /// - Local includes unsynced and synced entries
  /// - Remote includes server synced entries
  /// De-duplicates by `id` and sorts by `completedAt` desc.
  Future<List<PomodoroSession>> mergedSessionsForCurrentUser() async {
    final user = AuthService.instance.currentUser;
    final local = await DatabaseService.instance.getSessions(userId: user?.id);
    if (user == null) return local;
    List<PomodoroSession> remote = [];
    try {
      remote = await ApiService.instance.fetchSessionsForUser(user.id);
    } catch (_) {
      // If remote fetch fails (offline, server), still show local sessions.
      remote = [];
    }
    final map = <String, PomodoroSession>{};
    for (final s in local) {
      map[s.id] = s;
    }
    for (final s in remote) {
      map.putIfAbsent(s.id, () => s);
    }
    final all = map.values.toList();
    all.sort((a, b) => b.completedAt.compareTo(a.completedAt));
    return all;
  }
}